name: Email-Stuff
version: 2.00
abstract: A more casual approach to creating and sending Email:: emails
author: Adam Kennedy <cpan@ali.as>, L<http://ali.as/>
license: perl
distribution_type: module
build_requires:
  Test::More: 0.47
  File::Spec: 0.80
  Email::Send::Test: 2.00
requires:
  perl: 5.005
  Carp: 0
  prefork: 1.00
  Clone: 0.13
  Email::MIME: 1.6
  Email::MIME::Creator: 1.3
  Email::Simple::Headers: 1.01
  Email::Send: 2.00
  File::Type: 0.22
  File::Slurp: 9999.04
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.45
