name: Email-Stuff
version: 0.07
abstract: A quick and casual approach to creating and sending emails
author: Adam Kennedy <cpan@ali.as>
license: perl
distribution_type: module
build_requires:
  Test::More: 0.47
  File::Spec: 0.82
  Email::Send::Test: 0.02
requires:
  perl: 5.005
  prefork: 0.02
  Clone: 0.13
  Email::MIME: 1.6
  Email::MIME::Creator: 1.3
  Email::Simple::Headers: 1.01
  Email::Send: 1.42
  File::Type: 0.22
  File::Slurp: 9999.04
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.37
