name: Email-Stuff
version: 0.06
abstract: Email stuff to people and things... and, like, stuff
author: Adam Kennedy<cpan@ali.as>
license: perl
distribution_type: module
build_requires:
  Test::More: 0.47
  File::Spec: 0.82
requires:
  perl: 5.005
  prefork: 0.02
  Clone: 0.13
  Email::MIME: 1.6
  Email::MIME::Creator: 1.3
  Email::Send: 1.42
  File::Type: 0.22
  File::Slurp: 9999.04
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.35
