
no_index: 
  directory: 
    - inc
    - t
generated_by: Module::Install version 0.55
distribution_type: module
version: 2.02
name: Email-Stuff
author: Adam Kennedy <cpan@ali.as>, L<http://ali.as/>
license: perl
build_requires: 
  Test::More: 0.47
  Email::Send::Test: 2.00
  File::Spec: 0.80
requires: 
  prefork: 1.00
  Email::MIME: 1.6
  Email::Send: 2.02
  Carp: 0
  perl: 5.005
  File::Type: 0.22
  Clone: 0.13
  Email::MIME::Creator: 1.3
  File::Slurp: 9999.04
  Email::Simple::Headers: 1.01
abstract: "A more casual approach to creating and sending Email:: emails"
