---
abstract: 'A more casual approach to creating and sending Email:: emails'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  Email::Send::Test: 2.04
  File::Spec: 0.80
  Test::More: 0.47
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Email-Stuff
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Email::MIME: 1.858
  Email::MIME::Creator: 1.451
  Email::Send: 2.185
  Email::Simple: 1.998
  File::Basename: 0
  File::Type: 0.22
  Params::Util: 0.23
  perl: 5.005
  prefork: 1.01
resources:
  license: http://dev.perl.org/licenses/
version: 2.07
