abstract: 'A more casual approach to creating and sending Email:: emails'
author: 'Adam Kennedy <cpan@ali.as>, L<http://ali.as/>'
build_requires:
  Email::Send::Test: 2.00
  File::Spec: 0.80
  Test::More: 0.47
distribution_type: module
generated_by: Module::Install version 0.63
license: perl
name: Email-Stuff
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Clone: 0.13
  Email::MIME: 1.6
  Email::MIME::Creator: 1.3
  Email::Send: 2.02
  Email::Simple::Headers: 1.01
  File::Slurp: 9999.04
  File::Type: 0.22
  perl: 5.005
  prefork: 1.00
version: 2.03
